import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export type Language = "de" | "en" | "tr";

export const languages = {
  de: "Deutsch",
  en: "English",
  tr: "Türkçe"
} as const;

export const translations = {
  de: {
    overview: "Gesamtübersicht",
    kpiDescription: "Alle wichtigen KPIs auf einen Blick.",
    websitePerformance: "Website Performance",
    websiteVisitors: "Website Besucher",
    pageViews: "Seitenaufrufe",
    activeForms: "Aktive Formulare",
    discoveredPages: "Erfasste Seiten",
    onAllPages: "Auf allen Seiten",
    autoDetected: "Automatisch erkannt",
    vsLastMonth: "vs. letzter Monat",
    socialMedia: "Social Media Performance",
    organicReach: "Organic Reach",
    socialEngagement: "Social Engagement",
    adImpressions: "Ad Impressionen",
    socialROI: "Social ROI",
    vsLastWeek: "vs. letzte Woche",
    vsLastQuarter: "vs. letztes Quartal",
    googleAds: "Google Ads Performance",
    clicks: "Klicks",
    impressions: "Impressionen",
    ctr: "CTR",
    conversionRate: "Conversion Rate",
    websiteTraffic: "Website Traffic",
    websiteTrafficDescription: "Übersicht über Ihre Website-Besucher und Aktivitäten.",
    enterWebsiteUrl: "Website URL eingeben (z.B. https://example.com)",
    scanning: "Scanne...",
    scanWebsite: "Website scannen",
    scanError: "Fehler",
    enterUrl: "Bitte geben Sie eine URL ein",
    scanComplete: "Scan abgeschlossen",
    pagesAndForms: "Seiten und Formulare gefunden",
    scanFailed: "Scan-Fehler",
    checkUrlAndRetry: "Überprüfen Sie die URL und versuchen Sie es erneut",
    scanOptions: "Scan-Optionen",
    singleUrlScan: "Nur diese URL scannen (keine Unterseiten)",
    includedUrls: "Eingeschlossene URLs",
    addUrl: "URL hinzufügen",
    excludedUrls: "Ausgeschlossene URLs",
    discoveredPagesAndForms: "Gefundene Seiten & Formulare",
    discoveredPagesDescription: "Übersicht aller erkannten Seiten und deren Formulare",
    page: "Seite",
    forms: "Formulare",
    details: "Details",
    fields: "Felder",
    successPageExists: "Erfolgsseite vorhanden",
    steps: "Schritte",
    currentVisitors: "Aktuelle Besucher",
    ga4Required: "GA4 Integration erforderlich",
    avgVisitTime: "Durchschn. Besuchszeit"
  },
  en: {
    overview: "Overview",
    kpiDescription: "All important KPIs at a glance.",
    websitePerformance: "Website Performance",
    websiteVisitors: "Website Visitors",
    pageViews: "Page Views",
    activeForms: "Active Forms",
    discoveredPages: "Discovered Pages",
    onAllPages: "On all pages",
    autoDetected: "Automatically detected",
    vsLastMonth: "vs. last month",
    socialMedia: "Social Media Performance",
    organicReach: "Organic Reach",
    socialEngagement: "Social Engagement",
    adImpressions: "Ad Impressions",
    socialROI: "Social ROI",
    vsLastWeek: "vs. last week",
    vsLastQuarter: "vs. last quarter",
    googleAds: "Google Ads Performance",
    clicks: "Clicks",
    impressions: "Impressions",
    ctr: "CTR",
    conversionRate: "Conversion Rate",
    websiteTraffic: "Website Traffic",
    websiteTrafficDescription: "Overview of your website visitors and activities.",
    enterWebsiteUrl: "Enter website URL (e.g. https://example.com)",
    scanning: "Scanning...",
    scanWebsite: "Scan Website",
    scanError: "Error",
    enterUrl: "Please enter a URL",
    scanComplete: "Scan Complete",
    pagesAndForms: "pages and forms found",
    scanFailed: "Scan Failed",
    checkUrlAndRetry: "Check the URL and try again",
    scanOptions: "Scan Options",
    singleUrlScan: "Scan only this URL (no subpages)",
    includedUrls: "Included URLs",
    addUrl: "Add URL",
    excludedUrls: "Excluded URLs",
    discoveredPagesAndForms: "Discovered Pages & Forms",
    discoveredPagesDescription: "Overview of all detected pages and their forms",
    page: "Page",
    forms: "Forms",
    details: "Details",
    fields: "Fields",
    successPageExists: "Success page exists",
    steps: "Steps",
    currentVisitors: "Current Visitors",
    ga4Required: "GA4 Integration required",
    avgVisitTime: "Avg. Visit Time"
  },
  tr: {
    overview: "Genel Bakış",
    kpiDescription: "Tüm önemli KPI'lar bir bakışta.",
    websitePerformance: "Web Sitesi Performansı",
    websiteVisitors: "Web Sitesi Ziyaretçileri",
    pageViews: "Sayfa Görüntülemeleri",
    activeForms: "Aktif Formlar",
    discoveredPages: "Keşfedilen Sayfalar",
    onAllPages: "Tüm sayfalarda",
    autoDetected: "Otomatik algılandı",
    vsLastMonth: "geçen aya göre",
    socialMedia: "Sosyal Medya Performansı",
    organicReach: "Organik Erişim",
    socialEngagement: "Sosyal Etkileşim",
    adImpressions: "Reklam Gösterimleri",
    socialROI: "Sosyal ROI",
    vsLastWeek: "geçen haftaya göre",
    vsLastQuarter: "geçen çeyreğe göre",
    googleAds: "Google Ads Performansı",
    clicks: "Tıklamalar",
    impressions: "Gösterimler",
    ctr: "TTO",
    conversionRate: "Dönüşüm Oranı",
    websiteTraffic: "Web Sitesi Trafiği",
    websiteTrafficDescription: "Web sitesi ziyaretçileriniz ve aktivitelerinize genel bakış.",
    enterWebsiteUrl: "Web sitesi URL'si girin (örn. https://example.com)",
    scanning: "Taranıyor...",
    scanWebsite: "Siteyi Tara",
    scanError: "Hata",
    enterUrl: "Lütfen bir URL girin",
    scanComplete: "Tarama Tamamlandı",
    pagesAndForms: "sayfa ve form bulundu",
    scanFailed: "Tarama Hatası",
    checkUrlAndRetry: "URL'yi kontrol edin ve tekrar deneyin",
    scanOptions: "Tarama Seçenekleri",
    singleUrlScan: "Sadece bu URL'yi tara (alt sayfalar dahil değil)",
    includedUrls: "Dahil Edilen URL'ler",
    addUrl: "URL Ekle",
    excludedUrls: "Hariç Tutulan URL'ler",
    discoveredPagesAndForms: "Bulunan Sayfalar ve Formlar",
    discoveredPagesDescription: "Tespit edilen tüm sayfalar ve formlarına genel bakış",
    page: "Sayfa",
    forms: "Formlar",
    details: "Detaylar",
    fields: "Alanlar",
    successPageExists: "Başarı sayfası mevcut",
    steps: "Adımlar",
    currentVisitors: "Mevcut Ziyaretçiler",
    ga4Required: "GA4 Entegrasyonu gerekli",
    avgVisitTime: "Ort. Ziyaret Süresi"
  }
} as const;

export function getStoredLanguage(): Language {
  return (localStorage.getItem("language") as Language) || "de";
}

export function setStoredLanguage(lang: Language) {
  localStorage.setItem("language", lang);
}
