// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjmztgdvdajbnjvypime.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbXp0Z2R2ZGFqYm5qdnlwaW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzk4ODgsImV4cCI6MjA1NTc1NTg4OH0.9MlWZiXfVB_yDIrQ1putKB0m46CM9t2ha85aJqcg8Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);